apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-keys
  namespace: authentik
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: authentik-keys
  data:
  - secretKey: postgres_passwd
    remoteRef:
      key: secret/authentik
      property: postgres_passwd
  - secretKey: secret_key
    remoteRef:
      key: secret/authentik
      property: secret_key