---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  valuesFrom:
    - kind: Secret
      name: authentik-keys
      valuesKey: postgres_passwd
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-keys
      valuesKey: postgres_passwd
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: authentik-keys
      valuesKey: secret_key
      targetPath: authentik.secret_key
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 5m0s
  values:
    image:
      tag: "2022.4.1"
    authentik:
      error_reporting:
        enabled: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      enabled: true
      hosts:
      - host: authentik.gaia.devusb.us
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - authentik.gaia.devusb.us
        secretName: authentik-tls
    postgresql:
      enabled: true
      image:
        repository: postgres
        tag: 11.13
    redis:
      enabled: true
      image: 
        repository: redis
        tag: 6.2.5

