apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/authentik/"
  postBuild:
    substituteFrom:
      - kind: Secret
        name: authentik-keys