---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: "1.3.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  interval: 10m0s
  values:
    ingress:
      enabled: true
      host: longhorn.gaia.devusb.us
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls: true
      tlsSecret: longhorn-tls
    persistence:
      defaultClassReplicaCount: 2
    longhornManager:
      priorityClass: ~
      tolerations:
        - effect: "NoSchedule"
          key: "node-role.kubernetes.io/master"
          operator: "Exists"
      nodeSelector: {}

