---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-subnet-router
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gtaylor
  interval: 1m0s
  values:
    tailscale:
      auth:
        secretName: tailscale-key
      routes:
        - "192.168.0.0/16"


