apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f go-rss-pushover.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rpilocator
  name: rpilocator
  namespace: rss-pushover
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rpilocator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f go-rss-pushover.yaml
        kompose.version: 1.26.1 (HEAD)
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'rss-pushover'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/rss-pushover/rpilocator'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/data/rss-pushover/rpilocator" -}}
            export PUSHOVER_TOKEN="{{ .Data.data.token }}"
            export PUSHOVER_USER="{{ .Data.data.user }}"
          {{- end }}
      creationTimestamp: null
      labels:
        io.kompose.service: rpilocator
    spec:
      containers:
        - env:
            - name: CHECK_DELTA
              value: "0"
            - name: FEED_URL
              value: https://rpilocator.com/feed.rss
            - name: REFRESH_INTERVAL
              value: "1"
          image: devusb/go-rss-pushover:latest
          args:
            ['sh', '-c', 'source /vault/secrets/config && /go-rss-pushover']
          name: rpilocator
          resources: {}
      restartPolicy: Always
status: {}
