---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prom
  namespace: monitoring
spec:
  timeout: 600s
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        resources:
          requests:
            memory: 1Gi