---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  chart:
    spec:
      chart: blocky
      sourceRef:
        kind: HelmRepository
        name: blocky
  interval: 10m0s
  values:
    service:
      dns-tcp:
        type: LoadBalancer
        enabled: true
      dns-udp:
        type: LoadBalancer
        enabled: true

