---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: code-server
  namespace: code-server
spec:
  interval: 10m0s
  url: https://github.com/coder/code-server
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/ci/helm-chart/  

