apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mhelton
  namespace: code-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-mhelton
