apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mhelton
  namespace: code-server
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.137
    path: "/homes/mhelton"
  mountOptions:
    - nfsvers=4.2
