---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prom
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 10m0s
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: true
      service:
        type: LoadBalancer
      prometheusSpec:
        retention: 3d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
              selector: {}
