---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
  interval: 10m0s
  values:
    persistentVolumeClaim:
      accessModes:
      - ReadWriteMany
      enabled: true
      storageClass: longhorn
    replicaCount: 1
    serviceDhcp:
      enabled: false
    serviceDns:
      type: LoadBalancer
    serviceWeb:
      http:
        port: 8080
      https:
        enabled: false
      type: LoadBalancer

