apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f go-rss-pushover.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rpilocator
  name: rpilocator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rpilocator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f go-rss-pushover.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rpilocator
    spec:
      containers:
        - env:
            - name: CHECK_DELTA
              value: "0"
            - name: FEED_URL
              value: https://rpilocator.com/feed.rss
            - name: PUSHOVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pushover-rpilocator
                  key: token
            - name: PUSHOVER_USER
              valueFrom:
                secretKeyRef:
                  name: pushover-rpilocator
                  key: user
            - name: REFRESH_INTERVAL
              value: "1"
          image: devusb/go-rss-pushover:latest
          name: rpilocator
          resources: {}
      restartPolicy: Always
status: {}
