---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: atuin-db
  namespace: atuin
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    image:
      repository: postgres
      tag: 14
    auth:
      existingSecret: atuin-keys
      database: atuin
  interval: 1m0s

