---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: atuin-db
  namespace: atuin
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    global:
      image:
        repository: postgres
        tag: 14
      postgresql.auth.existingSecret: atuin-keys
  interval: 1m0s

