apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: atuin
  name: atuin
  namespace: atuin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: atuin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'atuin'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/atuin'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/data/atuin" -}}
            export ATUIN_DB_URI="postgres://{{ .Data.data.user }}:{{ .Data.data.password }}@atuin_db/atuin"
          {{- end }}
      creationTimestamp: null
      labels:
        io.kompose.service: atuin
    spec:
      containers:
      - command: 'sh'
      - args:
          ['-c', 'source /vault/secrets/config && /usr/local/bin/atuin server start']
        env:
        - name: ATUIN_HOST
          value: 0.0.0.0
        - name: ATUIN_OPEN_REGISTRATION
          value: "true"
        image: ghcr.io/ellie/atuin:main
        imagePullPolicy: ""
        name: atuin
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: atuin-config
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: atuin-config
        persistentVolumeClaim:
          claimName: atuin-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
status: {}
