---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  chart:
    spec:
      chart: blocky
      sourceRef:
        kind: HelmRepository
        name: blocky
  interval: 10m0s
  values:
    service:
      dns-tcp:
        type: LoadBalancer
        enabled: true
        annotations:
          metallb.universe.tf/allow-shared-ip: "blocky-dns"
          metallb.universe.tf/loadBalancerIPs: 192.168.20.121
      dns-udp:
        type: LoadBalancer
        enabled: true
        annotations:
          metallb.universe.tf/allow-shared-ip: "blocky-dns"
          metallb.universe.tf/loadBalancerIPs: 192.168.20.121
    ingress:
      main:
        enabled: true
        primary: true
        annotations: {}
        labels: {}
        hosts:
          -
            host: blocky.gaia.local
            paths:
              -
                path: /
                pathType: Prefix
                service:
                  name: blocky
                  port: 4000
    config: |
      port: 53
      httpPort: 4000
      upstream:
        default:
          - 1.1.1.1
      conditional:
        mapping:
          local: 192.168.20.1
          .: 192.168.20.1
      blocking:
        blackLists:
          ads:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          smart_home:
            - |
              n-devs.tplinkcloud.com
              n-deventry.tplinkcloud.com
        clientGroupsBlock:
          default:
            - ads
            - smart_home
      customDNS:
        customTTL: 1h
        mapping:
          hass.local: 192.168.10.119
          gaia.local: 192.168.20.13
          r2d2.local: 192.168.99.101
          unifi.local: 192.168.20.105 

