---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 10m0s
  values:
    configInline:
      address-pools:
      - addresses:
        - 192.168.20.10-192.168.20.50
        - 192.168.20.121/32
        name: default
        protocol: layer2

