apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atuin-keys
  namespace: atuin
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: atuin-keys
  data:
  - secretKey: postgres-password
    remoteRef:
      key: secret/atuin
      property: password