apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: tailscale-keys
spec:
  refreshInterval: "1m"
  externalSecretName: tailscale-keys
  namespaceSelector:
    matchLabels: 
      tailscale: true
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: tailscale-key
  data:
  - secretKey: AUTH_KEY
    remoteRef:
      key: secret/tailscale
      property: AUTH_KEY