apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-keys
  namespace: tailscale
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: tailscale-key
  data:
  - secretKey: AUTH_KEY
    remoteRef:
      key: secret/tailscale
      property: AUTH_KEY