---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  interval: 5m0s
  values:
    server:
      ingress:
        enabled: true
        labels: {}
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: ""
        pathType: Prefix
        activeService: true
        hosts:
          - host: vault.gaia.devusb.us
            paths: []
        tls:
          - secretName: vault-tls
            hosts:
              - vault.gaia.devusb.us
      ha:
        enabled: true
        replicas: 1
        raft:
          enabled: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}
            seal "awskms" {
              region     = "us-east-1"
              kms_key_id = "75f13e72-21e1-48b8-a2c3-d08038823d75"
              endpoint   = "https://kms.us-east-1.amazonaws.com"
            }
      extraSecretEnvironmentVars:
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: vault-kms
          secretKey: AWS_SECRET_ACCESS_KEY
        - envName: AWS_ACCESS_KEY_ID
          secretName: vault-kms
          secretKey: AWS_ACCESS_KEY_ID
      
